micronaut:
  application:
    name: invoices
  server:
    port: -1
consul:
  client:
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
db:
  name: 'invoices'
  collection: 'invoices'
netty:
  default:
    allocator:
      max-order: 3
