micronaut:
  application:
    name: invoices
    instance:
      id: ${random.shortuuid}
  config-client:
    enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            auth0:
              url: https://${AUTH0_DOMAIN}/.well-known/jwks.json
        enabled: true
        claims-validators:
          audience: ${AUTH0_AUDIENCE}
          issuer: https://${AUTH0_DOMAIN}/
    endpoints:
      oauth:
        enabled: false
      login:
        enabled: false
consul:
  client:
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
      prefer-ip-address: true
      health-path: /health
      check:
        http: true
    health-check: true
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
kafka.bootstrap.servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
db:
  name: 'invoices'
  collection: 'invoices'
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  health:
    enabled: true
    sensitive: false
