micronaut:
  application:
    name: invoices
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
db:
  name: 'invoices'
  collection: 'invoices'
netty:
  default:
    allocator:
      max-order: 3
